version: "3.8"

services:
  pc-nube:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: pc-nube
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/El_Salvador
      - SUBFOLDER=/
      - TITLE=PC-Cloud
      - CUSTOM_USER=admin
      - PASSWORD=admin123
      - LANG=es_SV.UTF-8
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    shm_size: "2gb"
    restart: unless-stopped
